version: "3.6"
services: 
  image-upload:
    image: ${ENVIRONMENT}-image-upload:${VERSION}
    build:
      context: ./
      dockerfile: Dockerfile
      target: ${ENVIRONMENT}
    ports:
      - "3000:3000"