version: "3.6"
services: 
  image-upload-local:
    image: ${LOCAL}-image-upload:${VERSION}
    build:
      context: ./
      dockerfile: Dockerfile
      target: ${LOCAL}
    ports:
      - "3000:3000"

  image-upload-prod:
    image: ${PRODUCTION}-image-upload:${VERSION}
    build:
      context: ./
      dockerfile: Dockerfile
      target: ${PRODUCTION}
    ports:
      - "4000:3000"